---
permalink: pretty
title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani Emo.,
  e Rmo. pri
tagline: an annotated digital edition
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url: 
baseurl: ''
gems:
- jekyll-sitemap
author:
  name: An Author
  url: 
  email: 
  twitter: 
version: 0.7
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/readux:thgg7_00000001.jp2/full/full/0/default.jpg
show_annotation_author: true
source_info:
  title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani
    Emo., e Rmo. pri
  via_readux: true
publication_info:
  title: All'Emo., e Rmo. Sigr. Pne. Colmo., Il Sig.r Cardinale Alessandro Albani
    Emo., e Rmo. pri
  date: '2019'
  editors: []
image_size:
  page:
    width: 9061
    height: 13088
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: false
    extra_js:
    - volume-page.js
    - hammer.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
